version: "3"
services:
  api:
    container_name: solar-limp-backend-container
    image: node:16.17.0
    working_dir: /usr/src/solar-limp-backend
    restart: always
    command: bash -c "npm i --omit=dev --silent && npm run debug"
    volumes:
      - ./:/usr/src/solar-limp-backend/
      - '/usr/src/solar-limp-backend/node_modules'
    ports:
      - "3000:3000"
      - "9222:9222"
  firebase-emulator:
    container_name: firebase-emulator-container
    build:
      context: .
      dockerfile: Dockerfile.firebase.emulator
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/src
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4000" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - 4000:4000
      - 9000:9000
    command: firebase emulators:start